-
  moreLoc: 1
  path: Android/Adapter的优化写法.md
  title: Adapter的优化写法
  date: 2016-11-14 22:29:00
  updated: 2017-11-30 14:27:00
  tags:
    - Android
  categories:
    - Android
-
  moreLoc: 3
  path: Android/Android Gradle权威指南 1 - Gradle入门.md
  title: Android Gradle权威指南 1 - Gradle入门
  date: 2017-12-09 23:31:00
  updated: 2017-12-09 23:31:00
  tags:
    - Android
  categories:
    - Android
-
  moreLoc: 6
  path: Android/Android内存泄露总结.md
  title: Android内存泄露总结
  date: 2016-10-26 22:19:00
  updated: 2016-11-15 09:51:00
  tags:
    - Android
  categories:
    - Android
-
  moreLoc: 3
  path: Android/Android异常之ANR.md
  title: Android异常之ANR
  date: 2016-11-03 13:36:00
  updated: 2016-11-03 13:36:00
  tags:
    - Android
  categories:
    - Android
-
  moreLoc: 5
  path: Android/Android异常之FC.md
  title: Android异常之FC
  date: 2016-11-03 13:38:00
  updated: 2016-11-03 13:38:00
  tags:
    - Android
  categories:
    - Android
-
  moreLoc: 2
  path: Android/Broadcast Receiver.md
  title: Broadcast Receiver
  date: 2016-11-14 22:29:00
  updated: 2016-11-14 22:29:00
  tags:
    - Android
  categories:
    - Android
-
  moreLoc: 6
  path: Android/CoordinatorLayout与Behavior的一己之见.md
  title: CoordinatorLayout与Behavior的一己之见
  date: 2016-10-10 20:11:00
  updated: 2016-12-04 14:24:00
  tags:
    - Android
  categories:
    - Android
-
  moreLoc: 5
  path: Android/Dagger2 的初步了解和使用.md
  title: Dagger2 的初步了解和使用
  date: 2017-03-13 12:10:00
  updated: 2017-03-13 12:10:00
  tags:
    - Android
  categories:
    - Android
-
  moreLoc: 1
  path: Android/Gradle 1 - AS工程目录及文件说明.md
  title: Gradle 1 - AS工程目录及文件说明
  date: 2017-11-30 15:24:00
  updated: 2017-11-30 15:24:00
  tags:
    - Android
  categories:
    - Android
-
  moreLoc: 1
  path: Android/Gradle 2 - 统一依赖管理.md
  title: Gradle 2 - 统一依赖管理
  date: 2017-11-30 15:24:01
  updated: 2017-11-30 15:24:01
  tags:
    - Android
  categories:
    - Android
-
  moreLoc: 1
  path: Android/Gradle 3 - 引入依赖.md
  title: Gradle 3 - 引入依赖
  date: 2017-11-30 15:24:02
  updated: 2017-11-30 15:24:02
  tags:
    - Android
  categories:
    - Android
-
  moreLoc: 1
  path: Android/Gradle 4 - 常用配置.md
  title: Gradle 4 - 常用配置
  date: 2017-11-30 15:24:03
  updated: 2017-11-30 15:24:03
  tags:
    - Android
  categories:
    - Android
-
  moreLoc: 1
  path: Android/HandlerThread - Handler - Thread.md
  title: HandlerThread - Handler - Thread
  date: 2017-11-30 15:24:04
  updated: 2017-11-30 15:24:04
  tags:
    - Android
  categories:
    - Android
-
  moreLoc: 1
  path: Android/IPC - AIDL.md
  title: IPC - AIDL
  date: 2018-04-24 22:44:00
  updated: 2018-05-14 21:12:00
  tags:
    - Android
  categories:
    - Android
-
  moreLoc: 1
  path: Android/Java和JavaScript交互.md
  title: Java和JavaScript交互
  date: 2016-11-03 10:53:00
  updated: 2016-12-04 14:24:00
  tags:
    - Android
  categories:
    - Android
-
  moreLoc: 1
  path: Android/Jenkins构建Android项目.md
  title: Jenkins构建Android项目
  date: 2017-05-15 18:01:00
  updated: 2017-05-15 18:01:00
  tags:
    - Android
  categories:
    - Android
-
  moreLoc: 1
  path: Android/Manifest中meta-data元素的配置与获取.md
  title: Manifest中meta-data元素的配置与获取
  date: 2017-03-18 19:36:00
  updated: 2017-11-30 14:27:00
  tags:
    - Android
  categories:
    - Android
-
  moreLoc: 1
  path: Android/Material Design 1 - 主题样式.md
  title: Material Design 1 - 主题样式
  date: 2017-11-22 20:30:00
  updated: 2017-11-30 15:24:00
  tags:
    - Android
  categories:
    - Android
-
  moreLoc: 1
  path: Android/Material Design 2 - Toolbar.md
  title: Material Design 2 - Toolbar
  date: 2017-11-30 15:24:01
  updated: 2017-11-30 15:24:01
  tags:
    - Android
  categories:
    - Android
-
  moreLoc: 1
  path: Android/Material Design 3 - TabLayout.md
  title: Material Design 3 - TabLayout
  date: 2017-11-30 15:24:02
  updated: 2017-11-30 15:24:02
  tags:
    - Android
  categories:
    - Android
-
  moreLoc: 1
  path: Android/Material Design 4 - AppBarLayout.md
  title: Material Design 4 - AppBarLayout
  date: 2017-11-30 15:24:03
  updated: 2017-11-30 15:24:03
  tags:
    - Android
  categories:
    - Android
-
  moreLoc: 1
  path: Android/Material Design 5 - CollapsingToolbarLayout.md
  title: Material Design 5 - CollapsingToolbarLayout
  date: 2017-11-30 15:24:04
  updated: 2017-11-30 15:24:04
  tags:
    - Android
  categories:
    - Android
-
  moreLoc: 1
  path: Android/Material Design 6 - FloatActionButton、Snackbar.md
  title: Material Design 6 - FloatActionButton、Snackbar
  date: 2017-11-30 15:24:05
  updated: 2017-11-30 15:24:05
  tags:
    - Android
  categories:
    - Android
-
  moreLoc: 1
  path: Android/Material Design 7 - DrawerLayout、NavigationView.md
  title: Material Design 7 - DrawerLayout、NavigationView
  date: 2017-11-30 15:24:06
  updated: 2017-11-30 15:24:06
  tags:
    - Android
  categories:
    - Android
-
  moreLoc: 1
  path: Android/NFC基础.md
  title: NFC基础
  date: 2017-11-30 14:27:00
  updated: 2017-11-30 14:27:00
  tags:
    - Android
  categories:
    - Android
-
  moreLoc: 1
  path: Android/Socket的简单使用.md
  title: Socket的简单使用
  date: 2017-11-30 14:27:00
  updated: 2017-11-30 14:27:00
  tags:
    - Android
  categories:
    - Android
-
  moreLoc: 1
  path: Android/inPreferredConfig参数.md
  title: inPreferredConfig参数
  date: 2017-11-30 14:27:00
  updated: 2017-11-30 14:27:00
  tags:
    - Android
  categories:
    - Android
-
  moreLoc: 1
  path: Android/数字，日期格式化.md
  title: 数字，日期格式化
  date: 2016-11-14 22:29:00
  updated: 2017-11-30 14:27:00
  tags:
    - Android
  categories:
    - Android
-
  moreLoc: 7
  path: Android/源码分析 - Router @chenenyu.md
  title: 源码分析 - Router @chenenyu
  date: 2018-08-29 14:58:00
  updated: 2018-08-29 14:58:00
  tags:
    - Android
  categories:
    - Android